export const paises = [
  {
    nombre: "Colombia",
    breveDescripcion: "País de América del Sur, conocido por su café y biodiversidad.",
    actividad1: "Visitar el Parque Nacional Natural Tayrona y disfrutar de sus playas.",
    url1: "/Tayrona.jpeg",
    razon1: "Experimenta la belleza natural y la tranquilidad de sus playas vírgenes.",
    actividad2: "Recorrer la Ciudad Perdida en la Sierra Nevada de Santa Marta.",
    url2: "/sierraNevada.jpeg",
    razon2: "Explora una de las civilizaciones más antiguas de América del Sur.",
    actividad3: "Explorar el Eje Cafetero y aprender sobre la producción de café.",
    url3: "/ejeCafetero.jpeg",
    razon3: "Descubre el origen del famoso café colombiano y sus paisajes únicos."
  },
  {
    nombre: "Francia",
    breveDescripcion: "País europeo famoso por su cultura, cocina y la Torre Eiffel.",
    actividad1: "Subir a la Torre Eiffel y disfrutar de la vista panorámica de París.",
    url1: "/public/tourEiffel.jpeg",
    razon1: "Disfruta de una vista icónica y panorámica de la 'Ciudad de la Luz'.",
    actividad2: "Visitar el Museo del Louvre y ver la Mona Lisa.",
    url2: "/public/louvre.jpeg",
    razon2: "Contempla una de las obras de arte más famosas del mundo en un museo de renombre.",
    actividad3: "Recorrer la región de la Provenza y sus campos de lavanda.",
    url3: "/public/provenza.jpeg",
    razon3: "Sumérgete en el aroma y la belleza de los infinitos campos de lavanda."
  },
  {
    nombre: "Japón",
    breveDescripcion: "Isla en Asia oriental, conocida por su tecnología avanzada y cultura tradicional.",
    actividad1: "Explorar los templos y santuarios de Kioto.",
    url1: "/public/kyoto.jpeg",
    razon1: "Descubre la espiritualidad y la historia en los templos antiguos.",
    actividad2: "Visitar el distrito de Akihabara en Tokio, famoso por la tecnología y la cultura otaku.",
    url2: "/public/akihabara.jpeg",
    razon2: "Sumérgete en el vibrante mundo de la tecnología y el anime.",
    actividad3: "Subir al Monte Fuji, la montaña más alta de Japón.",
    url3: "/public/monteFuji.jpeg",
    razon3: "Disfruta de una experiencia única al escalar la montaña sagrada de Japón."
  },
  {
    nombre: "Australia",
    breveDescripcion: "Nación insular en Oceanía, reconocida por su vida salvaje única y la Gran Barrera de Coral.",
    actividad1: "Bucear en la Gran Barrera de Coral, el arrecife de coral más grande del mundo.",
    url1: "/public/granBarrera.jpeg",
    razon1: "Admira la biodiversidad marina en un entorno natural incomparable.",
    actividad2: "Visitar la Ópera de Sídney, un ícono arquitectónico mundial.",
    url2: "/public/operaSydney.jpeg",
    razon2: "Conoce uno de los edificios más emblemáticos del mundo y su historia.",
    actividad3: "Explorar el Parque Nacional Kakadu y su rica fauna y flora.",
    url3: "/public/kakadu.jpeg",
    razon3: "Conéctate con la naturaleza en uno de los parques nacionales más grandes de Australia."
  },
  {
    nombre: "Egipto",
    breveDescripcion: "País en el noreste de África, hogar de las antiguas pirámides y el río Nilo.",
    actividad1: "Explorar las Pirámides de Giza y la Esfinge.",
    url1: "/public/giza.jpeg",
    razon1: "Descubre una de las Siete Maravillas del Mundo Antiguo.",
    actividad2: "Navegar por el río Nilo en un crucero tradicional.",
    url2: "/public/nilo.jpeg",
    razon2: "Vive la experiencia de navegar por el río que dio vida a una civilización.",
    actividad3: "Visitar el Museo Egipcio en El Cairo para ver tesoros antiguos.",
    url3: "/public/museoEgipcio.jpeg",
    razon3: "Admira los tesoros de una de las civilizaciones más antiguas del mundo."
  },
  {
    nombre: "Italia",
    breveDescripcion: "País europeo con una rica historia, famosa por su arte, arquitectura y gastronomía.",
    actividad1: "Visitar el Coliseo en Roma y explorar la antigua historia romana.",
    url1: "/public/coliseo.jpeg",
    razon1: "Revive la gloria de la Antigua Roma en un icónico anfiteatro.",
    actividad2: "Pasear por los canales de Venecia en góndola.",
    url2: "/public/venecia.jpeg",
    razon2: "Disfruta de un romántico paseo en góndola por los históricos canales.",
    actividad3: "Explorar la región vinícola de la Toscana.",
    url3: "/public/toscana.jpeg",
    razon3: "Degusta vinos finos en una de las regiones vinícolas más famosas del mundo."
  },
  {
    nombre: "Brasil",
    breveDescripcion: "El país más grande de América del Sur, conocido por sus selvas tropicales y el Carnaval de Río.",
    actividad1: "Visitar el Cristo Redentor en Río de Janeiro.",
    url1: "/public/cristoRedentor.jpeg",
    razon1: "Contempla la majestuosa vista de Río de Janeiro desde lo alto del Corcovado.",
    actividad2: "Explorar la Amazonía, la selva tropical más grande del mundo.",
    url2: "/public/amazonia.jpeg",
    razon2: "Sumérgete en la biodiversidad y el misterio de la selva más grande del planeta.",
    actividad3: "Disfrutar de las playas de Copacabana e Ipanema.",
    url3: "/public/copacabana.jpeg",
    razon3: "Relájate en las famosas playas de arena blanca de Río de Janeiro."
  },
  {
    nombre: "India",
    breveDescripcion: "País del sur de Asia, conocido por su diversidad cultural y el Taj Mahal.",
    actividad1: "Visitar el Taj Mahal en Agra, una de las Siete Maravillas del Mundo.",
    url1: "/public/tajMahal.jpeg",
    razon1: "Maravíllate ante la obra maestra de amor y arquitectura.",
    actividad2: "Explorar los templos de Varanasi, la ciudad sagrada en el río Ganges.",
    url2: "/public/varanasi.jpeg",
    razon2: "Experimenta la espiritualidad y las antiguas tradiciones en la ciudad más sagrada de India.",
    actividad3: "Recorrer los palacios y fortalezas de Rajastán.",
    url3: "/public/rajastan.jpeg",
    razon3: "Admira la majestuosidad y el esplendor de los palacios reales."
  },
  {
    nombre: "China",
    breveDescripcion: "El país más poblado del mundo, conocido por su antigua civilización y la Gran Muralla China.",
    actividad1: "Caminar por la Gran Muralla China.",
    url1: "/public/murallaChina.jpeg",
    razon1: "Recorre una de las estructuras más impresionantes jamás construidas.",
    actividad2: "Visitar la Ciudad Prohibida en Pekín.",
    url2: "/public/ciudadProhibida.jpeg",
    razon2: "Explora el palacio imperial mejor conservado de China.",
    actividad3: "Explorar el Ejército de Terracota en Xi'an.",
    url3: "/public/ejercitoTerracota.jpeg",
    razon3: "Descubre los antiguos guerreros que protegieron al primer emperador de China."
  },
  {
    nombre: "Sudáfrica",
    breveDescripcion: "País en el extremo sur de África, conocido por su biodiversidad y la historia del apartheid.",
    actividad1: "Hacer un safari en el Parque Nacional Kruger.",
    url1: "/public/kruger.jpeg",
    razon1: "Vive la emoción de ver animales salvajes en su hábitat natural.",
    actividad2: "Visitar Ciudad del Cabo y subir a la Montaña de la Mesa.",
    url2: "/public/ciudadDelCabo.jpeg",
    razon2: "Disfruta de una vista impresionante desde uno de los puntos más emblemáticos de Sudáfrica.",
    actividad3: "Explorar la Ruta Jardín, famosa por su belleza natural.",
    url3: "/public/rutaJardin.jpeg",
    razon3: "Recorre uno de los destinos más pintorescos del mundo."
  },
  {
    nombre: "México",
    breveDescripcion: "País en América del Norte, conocido por su rica cultura, cocina y antiguas civilizaciones.",
    actividad1: "Visitar las pirámides de Teotihuacán.",
    url1: "/public/teotihuacan.jpeg",
    razon1: "Explora las monumentales pirámides de una de las civilizaciones más poderosas de Mesoamérica.",
    actividad2: "Explorar las ruinas mayas de Chichén Itzá.",
    url2: "/public/chichenItza.jpeg",
    razon2: "Contempla una de las Nuevas Siete Maravillas del Mundo.",
    actividad3: "Relajarse en las playas de Cancún.",
    url3: "/public/cancun.jpeg",
    razon3: "Disfruta del sol y el mar en uno de los destinos turísticos más populares de México."
  }
];
